spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    com.paymentplatform.account: DEBUG
    org.springframework.web: DEBUG
