spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audit_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: audit-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.use.type.headers: false

logging:
  level:
    com.paymentplatform.audit: DEBUG
