spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fraud_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fraud-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

account-service:
  base-url: http://localhost:8081

ml-scoring-service:
  base-url: http://localhost:8090
logging:
  level:
    com.paymentplatform.fraud: DEBUG
