spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-processor-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.paymentplatform.fraud.event.FraudCheckCompletedEvent
  rabbitmq:
    host: localhost
    port: 5580
    username: guest
    password: guest

logging:
  level:
    com.paymentplatform.payment: DEBUG
