spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-processor-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.paymentplatform.paymentprocessor.event.FraudCheckCompletedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  rabbitmq:
    host: localhost
    port: 5580
    username: guest
    password: guest
    exchange: transfer.exchange
    queue: transfer.status.update
    routing-key: transfer.status.update

account-service:
  base-url: http://localhost:8081

kafka:
  topics:
    fraud-check-completed: fraud-check-completed
    payment-processed: payment-processed

logging:
  level:
    com.paymentplatform.paymentprocessor: DEBUG
