spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/query_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: query-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

logging:
  level:
    com.paymentplatform.query: DEBUG
