spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transfer_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: transfer-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  rabbitmq:
    host: localhost
    port: 5580
    username: guest
    password: guest
    exchange: transfer.exchange
    queue: transfer.status.update
    routing-key: transfer.status.update

account-service:
  base-url: http://localhost:8081

logging:
  level:
    com.paymentplatform.transfer: DEBUG
